### ISSUE TITLE
It works but maybe confusing...

### ISSUE THREAD

**Issue by crianonim** [fac18/week3-gmno-prrr-api#33]
If I understand correctly, you want to get the current value of selected radio within group:

https://github.com/fac18/week3-gmno-prrr-api/blob/d80e42ec9a95165a8f7296f28a464dfd89a88e49/js-folder/script.js#L3-L9

It works, well done.

What you do is ask for all the radios and iterate over them, then if it's checked you add value to an array.
1. Array will only hold one value, so why not use just a plain variable
2. You can just choose a selected radio and immediatelly cast to a Number:
```javascript
Number(document.querySelector('[name="stranger-friendly"]:checked').value)
```

Have a look!

**Comment by ReginaldJbeili** [comment]
Refactoring done! Thanks for the assist!
