### ISSUE TITLE
Purrrrfectly pleasing!

### ISSUE THREAD

**Issue by redahaq** [fac18/week3-gmno-prrr-api#41]
What a joy of a game, well done!

![](https://media.giphy.com/media/1KHBPmEOkv0B2/giphy.gif)
Ceiling cat thinks so too.

I was a munchkin cat!

I love so much about this web app, the design is clear and pleasing. What a lovely cat svg for the background.

Simple, intuitive and fun game; I love how responsive it is, expanding to two columns.

Your functions are really nice and interesting to read through too.

You should all be very prrrrroud. 🌟🐱

**Comment by renatadev** [comment]
Yayy!! Thank you, Reda! 

We're very prrroud indeed! 🐱
