### ISSUE TITLE
const vs let

### ISSUE THREAD

**Issue by crianonim** [fac18/week3-gmno-prrr-api#47]
My rant again :wink: 
Your code uses a lot of `let` and it does work, but if you read it, it's not clear when you define a variable as `let` and never reassign it.
I think every `let` you used (except in for loops) you could replace with `const`

See my ramblings last week:
https://github.com/fac18/week2-BDIM-fiasco/issues/41

**Comment by ReginaldJbeili** [comment]
changed most lets to const
